### ISSUE TITLE
init requires two arguments

### ISSUE THREAD

**Issue by zimzaz** [csu/quora-backup#6]
what's going on here?

red@pratchett:~/bin/quora-backup$ python backup.py Fred-Zimmerman
Traceback (most recent call last):
  File "backup.py", line 15, in <module>
    sync()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "backup.py", line 11, in sync
    q = QuoraBackup(user)
  File "/home/fred/bin/quora-backup/quorabackup/quora_backup.py", line 81, in __init__
    self.activity = quora.get_activity(user)
  File "/usr/local/lib/python2.7/dist-packages/quora/quora.py", line 155, in get_activity
    user = User()
TypeError: __init__() takes exactly 2 arguments (1 given)

**Comment by csu** [comment]
Whoops, sorry. We made some changes in csu/pyquora and it broke this. I'll have it fixed in a few minutes.

**Comment by csu** [comment]
Should be fixed now. You'll want to check out the latest version of quora-backup and reinstall dependencies with pip.

**Comment by zimzaz** [comment]
Works now.  Cool!  How can I go back in time and get my archive? ;-)

**Comment by csu** [comment]
You can't. See the project description:

> A syncing approach to backing up Quora answers, questions, votes, and follows. Rather than fetching your entire history of Quora activity all at once, quora-backup checks your recent Quora activity and saves only the new entries. Run it regularly to maintain a full backup.
